# Generated by Django 4.2.2 on 2023-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='', verbose_name='Телеграмм'),
        ),
    ]
