# Generated by Django 4.2.2 on 2023-07-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Телеграмм'),
        ),
    ]
